<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Example Analysis – project1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">project1</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./data_analysis.html" aria-current="page"> 
<span class="menu-text">Example Analysis</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#research-question" id="toc-research-question" class="nav-link active" data-scroll-target="#research-question">Research question:</a></li>
  <li><a href="#intended-audience" id="toc-intended-audience" class="nav-link" data-scroll-target="#intended-audience">Intended Audience:</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a></li>
  <li><a href="#data-source-and-dictionary" id="toc-data-source-and-dictionary" class="nav-link" data-scroll-target="#data-source-and-dictionary">Data Source and Dictionary</a>
  <ul class="collapse">
  <li><a href="#data-dictionary" id="toc-data-dictionary" class="nav-link" data-scroll-target="#data-dictionary">Data Dictionary</a></li>
  </ul></li>
  <li><a href="#exploratory-analysis" id="toc-exploratory-analysis" class="nav-link" data-scroll-target="#exploratory-analysis">Exploratory Analysis</a>
  <ul class="collapse">
  <li><a href="#snapshot-into-top-and-bottom-of-data" id="toc-snapshot-into-top-and-bottom-of-data" class="nav-link" data-scroll-target="#snapshot-into-top-and-bottom-of-data">Snapshot into Top and Bottom of Data</a></li>
  </ul></li>
  <li><a href="#meta-analysis" id="toc-meta-analysis" class="nav-link" data-scroll-target="#meta-analysis">Meta-Analysis</a>
  <ul class="collapse">
  <li><a href="#effect-size-calculation" id="toc-effect-size-calculation" class="nav-link" data-scroll-target="#effect-size-calculation">Effect Size Calculation</a></li>
  <li><a href="#effect-size-mean-compared-to-time-across-funtional-groups" id="toc-effect-size-mean-compared-to-time-across-funtional-groups" class="nav-link" data-scroll-target="#effect-size-mean-compared-to-time-across-funtional-groups">Effect Size (Mean) Compared to Time Across Funtional Groups</a></li>
  <li><a href="#distribution-of-study-means" id="toc-distribution-of-study-means" class="nav-link" data-scroll-target="#distribution-of-study-means">Distribution of Study Means</a></li>
  <li><a href="#meta-analysis-models" id="toc-meta-analysis-models" class="nav-link" data-scroll-target="#meta-analysis-models">Meta-Analysis Models</a></li>
  <li><a href="#confidence-intervals-of-each-study" id="toc-confidence-intervals-of-each-study" class="nav-link" data-scroll-target="#confidence-intervals-of-each-study">Confidence Intervals of Each Study</a></li>
  </ul></li>
  <li><a href="#conclusionsummary" id="toc-conclusionsummary" class="nav-link" data-scroll-target="#conclusionsummary">Conclusion/Summary:</a></li>
  <li><a href="#functions-used-in-data-analysis" id="toc-functions-used-in-data-analysis" class="nav-link" data-scroll-target="#functions-used-in-data-analysis">Functions used in data analysis:</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Example Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Statistical meta-analysis is a method used across studies to systematically combine and analyze data from multiple studies on a particular topic. Oftentimes, researchers encounter conflicting results across studies, i.e.&nbsp;a finding that appears statistically significant in one study but lacks significance in another. This variance could stem from differences in study designs, sample characteristics, or many other factors. Through meta-analysis, we can navigate through conflicting results, derive more reliable conclusions about the relationships between variables, and systematic approach to interpret this variability in findings across studies.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\images\meta_analysis_pyramid.jpg" class="img-fluid figure-img"></p>
<figcaption>Hierarchy of Scientific Evidence</figcaption>
</figure>
</div>
</div></div><p>In this report, we will practice meta-analysis using a dataset from the <strong>metadat</strong> package in R. This dataset contains 102 studies that examined the effects of elevated CO2 levels in woody plant mass by comparing above and below-ground biomass (measured in grams) of plants exposed to ambient CO2 levels (control group) versus elevated CO2 levels (treatment group).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Want to know more?
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you want to read more about meta-analysis, <a href="https://onlinelibrary.wiley.com/doi/book/10.1002/9780470743386">here</a> is a link to a book to learn more.</p>
</div>
</div>
<section id="research-question" class="level1">
<h1>Research question:</h1>
<p>We are interested in determining if there is an overall difference between in above and below-ground biomass of plants exposed to C02 levels (control group) versus elevated C02 levels (treatment group).</p>
</section>
<section id="intended-audience" class="level1">
<h1>Intended Audience:</h1>
<p>The intended audience for this report is students in statistics hoping to get quick overview about meta-analysis and see an example for conducting meta-analysis.</p>
</section>
<section id="analysis" class="level1">
<h1>Analysis</h1>
<p>We can begin by loading the data and the necessary packages to condudct meta-analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">repos =</span> <span class="fu">c</span>(<span class="at">CRAN =</span> <span class="st">"https://cran.rstudio.com/"</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"knitr"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"metadat"</span>) </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"meta"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"metafor"</span>) <span class="co"># calculate effect sizes and conduct meta-regression</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(metadat) </span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(meta)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(metafor)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="data-source-and-dictionary" class="level1">
<h1>Data Source and Dictionary</h1>
<p>The dataset consists of 102 studies with 20 variables. Eleven are numeric variables and nine are character variables. These studies compared above and below-ground biomass (measured in grams) of plants exposed to ambient CO2 levels (control group) versus elevated CO2 levels (treatment group).</p>
<p>This dataset comes from the <strong>metadat</strong> package, and the original study was conducted by Peter S. Curtis and Xianzhong Wang. The article can be found <a href="https://link.springer.com/article/10.1007/s004420050381">here</a>).</p>
<section id="data-dictionary" class="level2">
<h2 class="anchored" data-anchor-id="data-dictionary">Data Dictionary</h2>
<table class="caption-top table">
<caption>Data dictionary comes from https://cloud.r-project.org/web/packages/metadat/metadat.pdf:</caption>
<colgroup>
<col style="width: 60%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Variable Name</th>
<th style="text-align: left;">Variable Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>id</td>
<td style="text-align: left;">observation number</td>
</tr>
<tr class="even">
<td>paper</td>
<td style="text-align: left;">paper number</td>
</tr>
<tr class="odd">
<td>genus</td>
<td style="text-align: left;">name of species</td>
</tr>
<tr class="even">
<td>species</td>
<td style="text-align: left;">name of species</td>
</tr>
<tr class="odd">
<td>fungrp</td>
<td style="text-align: left;">plant functional group</td>
</tr>
<tr class="even">
<td>co2.ambi</td>
<td style="text-align: left;">ambient CO2 level control group</td>
</tr>
<tr class="odd">
<td>co2.elev</td>
<td style="text-align: left;">elevated CO2 level for treatmet group</td>
</tr>
<tr class="even">
<td>units</td>
<td style="text-align: left;">units for C02 exposure levels</td>
</tr>
<tr class="odd">
<td>time</td>
<td style="text-align: left;">maximum length of time days of C02 exposure</td>
</tr>
<tr class="even">
<td>pot</td>
<td style="text-align: left;">growing methods</td>
</tr>
<tr class="odd">
<td>method</td>
<td style="text-align: left;">CO2 exposure facility</td>
</tr>
<tr class="even">
<td>stock</td>
<td style="text-align: left;">planting stock code</td>
</tr>
<tr class="odd">
<td>xtrt</td>
<td style="text-align: left;">interacting treatment code</td>
</tr>
<tr class="even">
<td>level</td>
<td style="text-align: left;">interaction treatment level</td>
</tr>
<tr class="odd">
<td>m1i</td>
<td style="text-align: left;">mean plant mass under elevated CO2 level for treatment group</td>
</tr>
<tr class="even">
<td>sd1i</td>
<td style="text-align: left;">standard deviation of plant mass under elevated CO2 level for treatment group</td>
</tr>
<tr class="odd">
<td>n1i</td>
<td style="text-align: left;">number of observations under elevated CO2 level for treatment group</td>
</tr>
<tr class="even">
<td>m2i</td>
<td style="text-align: left;">mean plant mass under ambient CO2 level for control group</td>
</tr>
<tr class="odd">
<td>sd2i</td>
<td style="text-align: left;">standard deviation of plant mass under ambient CO2 level for control group</td>
</tr>
<tr class="even">
<td>n2i</td>
<td style="text-align: left;">number of observations under ambient CO2 level for control group</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="exploratory-analysis" class="level1">
<h1>Exploratory Analysis</h1>
<section id="snapshot-into-top-and-bottom-of-data" class="level2">
<h2 class="anchored" data-anchor-id="snapshot-into-top-and-bottom-of-data">Snapshot into Top and Bottom of Data</h2>
<p>First, we want to explore the data by examining the first and last few rows of the data, and subsetting the data based on specific variables of interest as they relate to our research question. These variables include the name of the plant species (species), functional group of the plants (fungrp), how long the plants were exposed to C02 (time), the CO2 exposure facility (method), the planting stock (stock), and the name of the species (genus).</p>
<p>In order to conduct our statistical analysis, we also need to obtain the mean plant mass for each study under the control group and treatment group (m1i and m2i), the standard deviations of each study (sd1i and sd2i), and the number of plants under the different treatments (n1i and n2i).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># loading in data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>metadata <span class="ot">&lt;-</span> metadat<span class="sc">::</span>dat.curtis1998</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># check for missing values</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># sum(is.na((metadata))) # no missing data found</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(metadata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  id paper   genus     species fungrp co2.ambi co2.elev units time pot method
1 21    44   ALNUS       RUBRA  N2FIX      350      650  ul/l   47 0.5     GC
2 22    44   ALNUS       RUBRA  N2FIX      350      650  ul/l   47 0.5     GC
3 27   121    ACER      RUBRUM  ANGIO      350      700   ppm   59 2.6     GH
4 32   121 QUERCUS      PRINUS  ANGIO      350      700   ppm   70 2.6     GH
5 35   121   MALUS   DOMESTICA  ANGIO      350      700   ppm   64 2.6     GH
6 38   121    ACER SACCHARINUM  ANGIO      350      700   ppm   50 2.6     GH
  stock xtrt   level     m1i      sd1i n1i    m2i      sd2i n2i
1  SEED FERT    HIGH  6.8169 1.7699820   3 3.9450 1.1157970   5
2  SEED FERT CONTROL  2.5961 0.6674662   5 2.2512 0.3275839   5
3  SEED NONE       .  2.9900 0.8560000   5 1.9300 0.5520000   5
4  SEED NONE       .  5.9100 1.7420000   5 6.6200 1.6310000   5
5  SEED NONE       .  4.6100 1.4070000   4 4.1000 1.2570000   4
6  SEED NONE       . 10.7800 1.1630000   5 6.4200 2.0260000   3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(metadata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     id paper   genus        species fungrp co2.ambi co2.elev units time  pot
97  755  2223  BETULA ALLEGHANIENSIS  ANGIO      350      700  ul/l  165 1.25
98  756  2223  BETULA ALLEGHANIENSIS  ANGIO      350      700  ul/l  165 1.25
99  757  2223  BETULA ALLEGHANIENSIS  ANGIO      350      700  ul/l  165 1.25
100 765  2224 QUERCUS          RUBRA  ANGIO      385      642  ul/l   60    6
101 774  2224    ACER      SACCHARUM  ANGIO      385      642  ul/l   60    6
102 783  2224 POPULUS    TREMULOIDES  ANGIO      385      642  ul/l   60    6
    method stock   xtrt level    m1i   sd1i n1i   m2i   sd2i n2i
97      GH  SEED   FERT   LOW   1.90 0.2205   6  1.48 0.1715   6
98      GH  SEED  LIGHT   LOW  14.45 1.6657   6  8.71 1.5187   6
99      GH  SEED FERT+L     .  16.98 0.5389   6 16.59 0.9553   6
100     GC  SEED   NONE     .  16.90 1.7321   3  7.20 2.5981   3
101     GC  SEED   NONE     .   7.20 1.7321   3  4.60 1.7321   3
102     GC  SEED   NONE     . 102.60 6.2354   3 69.70 3.6373   3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># subsetting based on variables of dat_interest</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>dat_interest <span class="ot">&lt;-</span> metadata <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(n1i, m1i, sd1i, n2i, m2i, sd2i, fungrp, time, method, stock, genus)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="meta-analysis" class="level1 page-columns page-full">
<h1>Meta-Analysis</h1>
<p>In order to conduct meta-analysis, we need to calculate the effect sizes of each study in our dataset.</p>
<section id="effect-size-calculation" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="effect-size-calculation">Effect Size Calculation</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create data frame of effect sizes</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>effect_size_dat <span class="ot">&lt;-</span> <span class="fu">escalc</span>(<span class="st">"SMD"</span>, <span class="at">n1i =</span> n1i, <span class="at">n2i =</span> n2i, <span class="at">m1i =</span> m1i, <span class="at">m2i =</span> m2i, <span class="at">sd1i =</span> sd1i, <span class="at">sd2i =</span> sd2i, <span class="at">data =</span> dat_interest, <span class="at">append =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>To get a better idea of the effect sizes (i.e.&nbsp;the standardized mean differences), we can summarize the means and variances of each study based on the functional group of the plant and the facility where they were exposed to CO2. This table is displayed the margin. Since all the effect sizes for each combination of methods and functional groups is positive, we expect that overall the plants in these categories who were exposed to more CO2 had higher plant masses than the plants exposed to the standard amount of CO2.</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># want to summarize data based on functional group (fungrp)and C02 exposure (method)</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>sum_table <span class="ot">&lt;-</span> effect_size_dat <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(fungrp, method) <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">k =</span> <span class="fu">n</span>(),</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_yi =</span> <span class="fu">mean</span>(yi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_vi =</span> <span class="fu">mean</span>(vi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span> <span class="co"># drops grouping once table is made</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(k)) <span class="sc">%&gt;%</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_yi =</span> <span class="fu">round</span>(mean_yi, <span class="dv">3</span>),</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_vi =</span> <span class="fu">round</span>(mean_vi, <span class="dv">3</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>sum_table <span class="sc">%&gt;%</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Moderator Summary by Functional Group and Method"</span>,</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">align =</span> <span class="st">"lccc"</span> <span class="co"># aligns columns, l=left and c=center</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

<div class="no-row-height column-margin column-container"><div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Moderator Summary by Functional Group and Method</caption>
<thead>
<tr class="header">
<th style="text-align: left;">fungrp</th>
<th style="text-align: center;">method</th>
<th style="text-align: center;">k</th>
<th style="text-align: center;">mean_yi</th>
<th style="text-align: left;">mean_vi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ANGIO</td>
<td style="text-align: center;">GH</td>
<td style="text-align: center;">58</td>
<td style="text-align: center;">1.314</td>
<td style="text-align: left;">0.780</td>
</tr>
<tr class="even">
<td style="text-align: left;">GYMNO</td>
<td style="text-align: center;">GC</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">1.158</td>
<td style="text-align: left;">0.245</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ANGIO</td>
<td style="text-align: center;">GC</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">2.565</td>
<td style="text-align: left;">1.258</td>
</tr>
<tr class="even">
<td style="text-align: left;">ANGIO</td>
<td style="text-align: center;">OTC</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">2.142</td>
<td style="text-align: left;">0.757</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GYMNO</td>
<td style="text-align: center;">GH</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">2.326</td>
<td style="text-align: left;">1.954</td>
</tr>
<tr class="even">
<td style="text-align: left;">N2FIX</td>
<td style="text-align: center;">GC</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1.207</td>
<td style="text-align: left;">0.579</td>
</tr>
</tbody>
</table>
</div></div></div>
</section>
<section id="effect-size-mean-compared-to-time-across-funtional-groups" class="level2">
<h2 class="anchored" data-anchor-id="effect-size-mean-compared-to-time-across-funtional-groups">Effect Size (Mean) Compared to Time Across Funtional Groups</h2>
<p>We can also plot the effect sizes against the time they were exposed to CO2, to see if there is a relationship between the differences in plant masses compared to the time the plants were exposed to CO2. We can separate this by functional group to see if the group adds an additional component to the relationship.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(effect_size_dat, <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> yi)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># scales = free_y means only x's are fixed</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> fungrp, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Effect Size vs. Time"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Comparing Relations Across Functional Groups"</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Time"</span>,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Standardized Mean Difference (yi)"</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"SMD = Standardized Mean Difference"</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data_analysis_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="distribution-of-study-means" class="level2">
<h2 class="anchored" data-anchor-id="distribution-of-study-means">Distribution of Study Means</h2>
<p>Lastly, we can examine the distribution of the standardized mean differences (SMD) for each study to get a better sense on how many studies have a positive SMD. A positive SMD value indiciates that the elevated CO2 levels result in a higher biomass for plants.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(effect_size_dat, <span class="fu">aes</span>(<span class="at">x =</span> yi)) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribution of Standardized Mean Differences (yi)"</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"We count the effect sizes that fall into specific SMD ranges"</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Standardized Mean Difference (yi)"</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Majority of SMD's are positive"</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data_analysis_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see that majority of the SMD’s are positive. This means that potentially the overall SMD obtained from our meta-analysis model could be significant, i.e.&nbsp;plants given more CO2 will have a higher biomass. We can run the full analysis model to determine if our insight is correct.</p>
</section>
<section id="meta-analysis-models" class="level2">
<h2 class="anchored" data-anchor-id="meta-analysis-models">Meta-Analysis Models</h2>
<p>There are two types of models we can use to conduct a meta-analysis study: fixed effect model and random effects model. Under the fixed effect model, we assume that all studies share a common, but unknown, true effect size. Under the random effects model, we assume that the true effect size is different for each study and that these true effect sizes are normally distributed about some average, unknown effect size. We can use the test of heterogeniuty to determine which model is bets for our data. We can then assess if our overall effect size, i.e.&nbsp;mean difference, is significant.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardized Mean Difference</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ====== calculates SMD for each study</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>SMD_results <span class="ot">&lt;-</span> <span class="fu">metacont</span>(n1i, m1i, sd1i, n2i, m2i, sd2i, <span class="at">sm =</span> <span class="st">"SMD"</span>, <span class="at">data =</span> metadata)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SMD_results)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        SMD             95%-CI %W(common) %W(random)
1    1.8222 [-0.0577;  3.7020]        0.4        0.8
2    0.5922 [-0.6899;  1.8743]        0.8        1.2
3    1.3286 [-0.1124;  2.7695]        0.6        1.1
4   -0.3798 [-1.6371;  0.8774]        0.8        1.2
5    0.3321 [-1.0715;  1.7356]        0.6        1.1
6    2.5137 [ 0.3058;  4.7216]        0.3        0.6
7    0.5405 [-1.1334;  2.2144]        0.5        0.9
8    2.0471 [-0.4056;  4.4997]        0.2        0.5
9    1.1710 [ 0.4951;  1.8468]        2.8        1.8
10   0.8035 [ 0.0796;  1.5275]        2.4        1.7
11   1.2478 [ 0.5881;  1.9076]        2.9        1.8
12   0.8135 [ 0.2229;  1.4042]        3.7        1.9
13   0.9234 [-0.1225;  1.9693]        1.2        1.4
14   0.4358 [-0.5592;  1.4309]        1.3        1.5
15   0.0687 [-0.9117;  1.0490]        1.3        1.5
16   0.3507 [-0.9040;  1.6054]        0.8        1.2
17   0.7625 [-0.0714;  1.5964]        1.8        1.6
18   0.0356 [-1.2041;  1.2754]        0.8        1.2
19   0.3999 [-0.8593;  1.6590]        0.8        1.2
20   0.5858 [-0.6954;  1.8670]        0.8        1.2
21   1.6208 [ 0.0911;  3.1504]        0.5        1.0
22   0.8149 [-0.5041;  2.1338]        0.7        1.2
23   0.8371 [-0.3642;  2.0385]        0.9        1.3
24   2.6024 [ 1.3501;  3.8547]        0.8        1.2
25   9.5026 [ 7.3444; 11.6609]        0.3        0.6
26   1.5618 [ 0.2029;  2.9208]        0.7        1.1
27   3.0319 [ 1.1840;  4.8797]        0.4        0.8
28   0.5020 [-0.9240;  1.9279]        0.6        1.1
29   0.9103 [-0.6034;  2.4240]        0.6        1.0
30  -0.2939 [-1.6937;  1.1058]        0.7        1.1
31   0.8706 [-0.6327;  2.3738]        0.6        1.0
32   0.8207 [-0.6700;  2.3113]        0.6        1.0
33   0.5385 [-0.3573;  1.4344]        1.6        1.6
34   1.6557 [ 0.6107;  2.7007]        1.2        1.4
35   1.2674 [ 0.2886;  2.2462]        1.3        1.5
36   1.3182 [ 0.3315;  2.3049]        1.3        1.5
37   0.2387 [-0.6416;  1.1191]        1.6        1.6
38   0.5022 [-0.3912;  1.3955]        1.6        1.6
39   3.0826 [-3.2691;  9.4343]        0.0        0.1
40   3.8360 [-3.9337; 11.6056]        0.0        0.1
41   2.0126 [-2.3921;  6.4174]        0.1        0.2
42   0.8117 [-1.7127;  3.3360]        0.2        0.5
43   1.2879 [ 0.5179;  2.0579]        2.2        1.7
44   0.3481 [-0.3507;  1.0470]        2.6        1.8
45   1.5619 [-2.0730;  5.1967]        0.1        0.3
46   0.4997 [-1.6913;  2.6908]        0.3        0.6
47   1.5460 [-2.0627;  5.1546]        0.1        0.3
48  -1.3882 [-4.7414;  1.9650]        0.1        0.3
49   3.8415 [-3.9386; 11.6217]        0.0        0.1
50   2.3499 [-2.6555;  7.3553]        0.1        0.2
51   0.5384 [-1.6876;  2.7644]        0.3        0.6
52   1.7594 [-2.2070;  5.7258]        0.1        0.2
53   1.7650 [-2.2110;  5.7410]        0.1        0.2
54   0.3397 [-1.7302;  2.4097]        0.3        0.7
55   1.0041 [-1.7734;  3.7815]        0.2        0.4
56  -0.0128 [-1.9729;  1.9473]        0.3        0.7
57   0.6599 [-1.6884;  3.0082]        0.2        0.6
58   0.1446 [-1.8358;  2.1249]        0.3        0.7
59   2.3289 [-2.6386;  7.2964]        0.1        0.2
60   2.5738 [-2.8381;  7.9858]        0.0        0.1
61   0.6969 [-1.6921;  3.0860]        0.2        0.6
62   0.2752 [-1.7576;  2.3080]        0.3        0.7
63   5.8589 [ 2.3898;  9.3280]        0.1        0.3
64   1.5139 [ 0.0181;  3.0098]        0.6        1.0
65   0.4956 [ 0.0892;  0.9020]        7.7        2.0
66   0.9688 [ 0.5450;  1.3926]        7.1        2.0
67   0.8106 [ 0.3938;  1.2274]        7.4        2.0
68   0.7546 [ 0.3400;  1.1692]        7.4        2.0
69   0.6466 [-0.2576;  1.5509]        1.6        1.6
70   1.3238 [ 0.3363;  2.3114]        1.3        1.5
71   1.1142 [ 0.1577;  2.0707]        1.4        1.5
72   1.4304 [ 0.4254;  2.4354]        1.3        1.5
73   1.2300 [ 0.2569;  2.2031]        1.4        1.5
74   2.2130 [ 1.0525;  3.3735]        0.9        1.3
75   2.5799 [ 0.6899;  4.4700]        0.4        0.8
76   0.6666 [-0.6266;  1.9599]        0.8        1.2
77   2.4663 [-2.7498;  7.6824]        0.0        0.1
78   6.0967 [-6.0123; 18.2058]        0.0        0.0
79   2.0771 [-2.4412;  6.5954]        0.1        0.2
80   2.1243 [-2.4775;  6.7261]        0.1        0.2
81   3.2603 [ 1.0723;  5.4484]        0.3        0.6
82   0.3042 [-0.8368;  1.4453]        1.0        1.3
83   2.8525 [ 1.0722;  4.6328]        0.4        0.8
84   2.8741 [ 1.0857;  4.6624]        0.4        0.8
85   1.6679 [ 0.2799;  3.0558]        0.7        1.1
86   3.5559 [ 1.5026;  5.6093]        0.3        0.7
87   0.9400 [-0.2788;  2.1589]        0.9        1.3
88   2.4148 [ 0.7917;  4.0378]        0.5        0.9
89   3.7148 [ 1.5972;  5.8324]        0.3        0.7
90   1.0962 [-0.1526;  2.3450]        0.8        1.2
91   0.2744 [-0.8649;  1.4137]        1.0        1.3
92   1.7776 [ 0.3584;  3.1968]        0.6        1.1
93   2.2293 [ 0.6690;  3.7895]        0.5        1.0
94  -1.5839 [-2.9488; -0.2190]        0.7        1.1
95   2.2885 [ 0.7085;  3.8685]        0.5        1.0
96   2.9292 [ 1.1202;  4.7382]        0.4        0.8
97   1.9620 [ 0.4875;  3.4366]        0.6        1.0
98   3.3230 [ 1.3624;  5.2837]        0.3        0.7
99   0.4640 [-0.6895;  1.6175]        1.0        1.3
100  3.5052 [-0.0571;  7.0675]        0.1        0.3
101  1.1977 [-0.7371;  3.1325]        0.3        0.8
102  5.1427 [ 0.2067; 10.0786]        0.1        0.2

Number of studies: k = 102
Number of observations: o = 1577 (o.e = 787, o.c = 790)

                        SMD           95%-CI     z  p-value
Common effect model  0.9615 [0.8484; 1.0745] 16.67 &lt; 0.0001
Random effects model 1.1550 [0.9482; 1.3619] 10.94 &lt; 0.0001

Quantifying heterogeneity (with 95%-CIs):
 tau^2 = 0.5019 [0.4137; 1.4285]; tau = 0.7085 [0.6432; 1.1952]
 I^2 = 52.0% [39.7%; 61.7%]; H = 1.44 [1.29; 1.62]

Test of heterogeneity:
      Q d.f.  p-value
 210.28  101 &lt; 0.0001

Details of meta-analysis methods:
- Inverse variance method
- Restricted maximum-likelihood estimator for tau^2
- Q-Profile method for confidence interval of tau^2 and tau
- Calculation of I^2 based on Q
- Hedges' g (bias corrected standardised mean difference; using exact formulae)</code></pre>
</div>
</div>
<p>Based on our output above, we can see the test of heterogeneity was statistically significant (p-value &lt; 0.0001). This indicates the random effects model would suit our data better. Additionally, the standardized mean difference (SMD) between treatment groups is sstatistically signficant, as the confidence interval for the SMD does not contain 0. Additionally, the estimated between-study variance is quantified at 0.3756, meaning the difference and 52% of the total variability in our SMD is due to the between study variability (heterogeniety).</p>
<p>The <strong>forest</strong> function allows us to see the results of our statistical meta-analysis through a plot. We can see the output below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">forest</span>(SMD_results)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data_analysis_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="confidence-intervals-of-each-study" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals-of-each-study">Confidence Intervals of Each Study</h2>
<p>Since the plot above can be complicated to read and is too large to display, we examine the confidence intervals of each effect size from our SMD analysis in a simplified graph. This can give us an idea of how many studies reported a signficant difference in biomasses for plants given elevated CO2. Based on the plot below, we see the confidence intervals of more than our studies contain 0, meaning there is not a statistically signficant relationship between the CO2 levels and plant bimass. However, despite this, the overall difference across all the studies combined is significant due to the weight of each studies.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># making data frame of confidence intervals</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>ci_dat <span class="ot">&lt;-</span> effect_size_dat <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">se =</span> <span class="fu">sqrt</span>(vi),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">ci_lo =</span> yi <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">ci_hi =</span> yi <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">study_id =</span> <span class="fu">row_number</span>()</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ci_dat, <span class="fu">aes</span>(<span class="at">x =</span> study_id, <span class="at">y =</span> yi, <span class="at">ymin =</span> ci_lo, <span class="at">ymax =</span> ci_hi)) <span class="sc">+</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>() <span class="sc">+</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Effect Sizes of Each Study with 95% CIs"</span>,</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"True Effect Size is SMD = 0"</span>,</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Study index"</span>,</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Standardized Mean Difference (yi)"</span>,</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"CIs computed as yi ± 1.96*SE where yi = SMD of study"</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data_analysis_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>There are some additional meta-analysis tools that can be used such as meta-regression, and using Egger’s regression test to quantify potential publication bias. You can read more about <a href="https://casp-uk.net/news/understanding-meta-regression/#:~:text=Start%20by%20gathering%20relevant%20studies,and%20precision%20of%20your%20findings.">meta-regression</a> <a href="https://ebm.bmj.com/content/24/2/53">publication bias</a> by clicking the links provided.</p>
</div>
</div>
</section>
</section>
<section id="conclusionsummary" class="level1">
<h1>Conclusion/Summary:</h1>
<p>This report serves as an example for conducting a meta-analysis study. We aimed to determine if there was an overall difference between in above and below-ground biomass of plants exposed to C02 levels (control group) versus elevated C02 levels, using data from the <strong>metadat</strong> package.</p>
<p>Out of the 102 studies, about less than half are statistically significant. Based on the test of heterogeneity results conducted in our analysis, we reject the null hypothesis that all studies share a common effect size and conclude there exists variation in the mean differences reported among the studies. Thus the random effects-model is the more approriate model to account for this variation in calculating the overall standardized mean difference (SMD) across all studies. Our overall reported SMD is 1.155.</p>
<p>Because the SMD is greater than 0, we conclude that elevated CO2 levels are associated with a significant increase in woody plant mass relative to ambient CO2 levels. Therefore, the biomass of woody plants is higher for elevated CO2 levels compared to the biomass of woody plants for ambient CO2 levels.</p>
</section>
<section id="functions-used-in-data-analysis" class="level1">
<h1>Functions used in data analysis:</h1>
<ol type="1">
<li>From dyplr: select, group_by, summarize, arrange, mutate</li>
<li>From ggplot: geom_histogram, geom_pointrange, geom_point</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>